package com.teamdev.meador.compiler;

/**
 * Enumeration of implemented Meador program elements.
 */
public enum ProgramElement {
    LIST_OF_STATEMENTS,

    CONDITIONAL_OPERATOR,
    FOR_LOOP,
    WHILE_LOOP,
    SWITCH_OPERATOR,
    DATA_STRUCTURE_DECLARATION,
    PROCEDURE,
    STRUCTURE_FIELD_ASSIGNMENT,
    VARIABLE_ASSIGNMENT,

    EXPRESSION,

    DATA_STRUCTURE_INSTANCE,

    NUMERIC_OPERAND,
    NUMERIC_BRACKETS,
    NUMBER,
    FUNCTION,
    NUMERIC_EXPRESSION,

    BOOLEAN_EXPRESSION,
    BOOLEAN_OPERAND,
    BOOLEAN_LITERAL,
    BOOLEAN_BRACKETS,
    RELATIONAL_EXPRESSION,

    STRING_EXPRESSION,
    STRING_LITERAL,

    READ_VARIABLE,
    UNARY_PREFIX_EXPRESSION,
    UNARY_POSTFIX_EXPRESSION,
    VARIABLE_VALUE,
    STRUCTURE_FIELD_VALUE,
}
