package com.teamdev.meador.compiler;

public enum StatementType {
    PROGRAM,

    CODE_BLOCK,

    FOR,
    SWITCH,
    PROCEDURE,
    VARIABLE_DECLARATION,

    CONDITIONAL_OPERATOR,

    EXPRESSION,

    NUMERIC_OPERAND,
    NUMERIC_BRACKETS,
    NUMBER,
    FUNCTION,
    NUMERIC_EXPRESSION,

    BOOLEAN_EXPRESSION,
    BOOLEAN_OPERAND,
    BOOLEAN_LITERAL,
    BOOLEAN_BRACKETS,
    RELATIONAL_EXPRESSION,

    STRING_EXPRESSION,
    STRING_LITERAL,

    READ_VARIABLE,
    UNARY_PREFIX_EXPRESSION,
    UNARY_POSTFIX_EXPRESSION,
    VARIABLE_VALUE
}
