package com.teamdev.meador.compiler;

public enum StatementType {
    PROGRAM,

    CODE_BLOCK,

    VARIABLE_DECLARATION,
    PROCEDURE,
    SWITCH,

    EXPRESSION,
    NUMERIC_EXPRESSION,
    RELATIONAL_EXPRESSION,

    OPERAND,
    NUMBER,
    BRACKETS,
    FUNCTION,
    READ_VARIABLE,

    VARIABLE_VALUE,
    UNARY_PREFIX_EXPRESSION,
    UNARY_POSTFIX_EXPRESSION,
}
