package com.teamdev.meador.compiler;

public enum StatementType {
    PROGRAM,

    CODE_BLOCK,

    VARIABLE_DECLARATION,
    PROCEDURE,
    SWITCH,

    EXPRESSION,
    NUMERIC_EXPRESSION,
    RELATIONAL_EXPRESSION,

    READ_VARIABLE,

    OPERAND,
    NUMBER,
    BRACKETS,
    FUNCTION,
    VARIABLE_VALUE,
    BOOLEAN_OPERAND,
    NUMERIC_OPERAND,
    STRING_LITERAL,
    BOOLEAN_BRACKETS,
    NUMERIC_BRACKETS,
    BOOLEAN_LITERAL,
    BOOLEAN_EXPRESSION,
    STRING_EXPRESSION,

    UNARY_PREFIX_EXPRESSION, UNARY_POSTFIX_EXPRESSION, FOR
}
